type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "SQL Script"
      parameters:
        componentName: "Start"
    SQL Script:
      type: "sql-executor"
      parameters:
        componentName: "SQL Script"
        scriptLocation: "File"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        fileName: "Maia Init/init_maia_data.sql"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    SQL Script:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
